/*
 * Personal Task Manager
 * Copyright (c) 2026 Vitalii Yeremenko
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 */
package com.evsoft.mapper;

import com.evsoft.dto.TaskRequest;
import com.evsoft.dto.TaskResponse;
import com.evsoft.model.Task;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingConstants;
import org.mapstruct.MappingTarget;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
public interface TaskMapper {

    // Map incoming DTO to Database Entity
    // Ignore ID as it's generated by the database
    @Mapping(target = "id", ignore = true)

    @Mapping(target = "title")

    // New tasks are created as 'not completed' by default
    @Mapping(target = "completed", constant = "false")

    Task toEntity(TaskRequest request);
    TaskResponse toResponse(Task task);

    @Mapping(target = "id", ignore = true)
    void updateEntityFromDto(TaskRequest dto, @MappingTarget Task entity);
}
